import "./globals.css";
import Header from "../components/header/Header";
import Footer from "../components/footer/Footer";
import { MyContextProvider } from "./context/MyContextProvider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body>
        <MyContextProvider>
          <Header />
          {children}
          <Footer />
        </MyContextProvider>
      </body>
    </html>
  );
}
